import doctor1 from "../../public/doctor-1.svg";
import doctor2 from "../../public/doctor-2.svg";
import doctor3 from "../../public/doctor-3.svg";
import doctor4 from "../../public/doctor-4.svg";

export const doctors = [
  {
    id: 1,
    name: "Dr. Tejas Sharma",
    phone: "+91 98765 43210",
    expertise: "Gynaecology",
    gender: "Male",
    mode: "In-Person & Online",
    fee: "₹1,500/-",
    image: doctor1,
    expanded: true,
  },
  {
    id: 2,
    name: "Dr. Tejas Sharma",
    phone: "+91 98765 43210",
    expertise: "Gynaecology",
    gender: "Male",
    mode: "In-Person & Online",
    fee: "₹1,500/-",
    image: doctor2,
  },
  {
    id: 3,
    name: "Dr. Tejas Sharma",
    phone: "+91 98765 43210",
    expertise: "Gynaecology",
    gender: "Male",
    mode: "In-Person & Online",
    fee: "₹1,500/-",
    image: doctor3,
  },
  {
    id: 4,
    name: "Dr. Tejas Sharma",
    phone: "+91 98765 43210",
    expertise: "Gynaecology",
    gender: "Male",
    mode: "In-Person & Online",
    fee: "₹1,500/-",
    image: doctor4,
  },
  {
    id: 5,
    name: "Dr. Tejas Sharma",
    phone: "+91 98765 43210",
    expertise: "Gynaecology",
    gender: "Male",
    mode: "In-Person & Online",
    fee: "₹1,500/-",
    image: doctor4,
  },
  {
    id: 6,
    name: "Dr. Tejas Sharma",
    phone: "+91 98765 43210",
    expertise: "Gynaecology",
    gender: "Male",
    mode: "In-Person & Online",
    fee: "₹1,500/-",
    image: doctor4,
  },
  {
    id: 7,
    name: "Dr. Tejas Sharma",
    phone: "+91 98765 43210",
    expertise: "Gynaecology",
    gender: "Male",
    mode: "In-Person & Online",
    fee: "₹1,500/-",
    image: doctor4,
  },
];
